routes/web.php
<?php

namespace App\Http\Controllers;

use App\Models\ProdukHukum;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/loginView', function () {
    return view('login');
});

Route::get('/dashboardPublic', function () {
    return view('dashboardPublic');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::get('/cariDashboardPublic', function () {
    return view('dashboardPublic');
});

Route::get('/caridashboard', function () {
    return view('dashboard');
});

Route::get('/password', function () {
    return view('pengaturan/password');
});

// Auth::routes();

Route::resource('pengaturan', PengaturanController::class);
Route::resource('usulan', UsulanController::class);
Route::resource('resume', ResumeController::class);
Route::resource('perda', PerdaController::class);
Route::resource('pergub', PergubController::class);
Route::resource('skgub', SkgubController::class);
Route::resource('skkaban', SkkabanController::class);
Route::resource('sksekda', SksekdaController::class);
Route::resource('user', UserController::class);
Route::resource('produkHukum', ProdukHukumController::class);
Route::resource('panduan', PanduanController::class);
Route::get('usulanAdmin', 'App\Http\Controllers\UsulanController@UsulanAdmin')->name('usulanAdmin');
Route::post('change-password', 'App\Http\Controllers\UserController@updatePassword')->name('update-password');
Route::post('uploadProdukPerda', 'App\Http\Controllers\PerdaController@uploadProdukPerda')->name('uploadProdukPerda');


Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('/cariusulan', [UsulanController::class, 'cariusulan'])->name('cariusulan');

Route::get('/usulanDetail', [UsulanController::class, 'usulanDetail'])->name('usulanDetail');
Route::get('/detailProdukHukum', [ProdukHukumController::class, 'detailProdukHukum'])->name('detailProdukHukum');
Route::get('/detailPanduan', [PanduanController::class, 'detailPanduan'])->name('detailPanduan');
Route::get('/resumeDetail', [ResumeController::class, 'resumeDetail'])->name('resumeDetail');
Route::get('/resumeDetailPublic', [ResumeController::class, 'resumeDetailPublic'])->name('resumeDetailPublic');
Route::get('/resumePublic', [ResumeController::class, 'resumePublic'])->name('resumePublic');
Route::get('/downloadPanduan', [PanduanController::class, 'downloadPanduan'])->name('downloadPanduan');

Route::get('/export', [ResumeController::class, 'export'])->name('export');

Route::get('/cariUsulanDetail', [UsulanController::class, 'cariUsulanDetail'])->name('cariUsulanDetail');
Route::get('/cariUsulanAdmin', [UsulanController::class, 'cariUsulanAdmin'])->name('cariUsulanAdmin');

Route::get('/exportResume', [ResumeController::class, 'exportexcel'])->name('exportResume');
Route::get('/cariResume', [ResumeController::class, 'cariResume'])->name('cariResume');

app/Models/ProdukHukum.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProdukHukum extends Model
{

    use HasFactory;
    public $table = "file_produk_hukum";

    protected $fillable = [
        'nomor_surat',
        'judul',
        'berkas',
        'deskripsi',
        'jenis',
        'status',
        'catatan',
        'nip',
        'berkas_catatan',
        'link_terkait'
    ];
}

app/Http/Controllers/ProdukHukumController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Models\ProdukHukum;
use Session;


class ProdukHukumController extends Controller
{

    public function index()
    {
        $selects = DB::table('file_produk_hukum')
            ->get();

        return view('produkHukum.index', compact('selects'));
    }

    /**
     * create
     *
     * @return void
     */
    public function create()
    {
        return view('produkHukum.create');
    }

    /**
     * store
     *
     * @param  mixed $request
     * @return void
     */
    public function store(Request $request)
    {
        // echo ("request");
        print_r($request->post());
        // echo ($request["store"]);
        $data = new ProdukHukum();

        $file = $request->file;

        $filename = time() . '.' . $file->getClientOriginalExtension();
        $request->file->move('assetes', $filename);

        $data->berkas = $filename;
        $data->nomor_surat = $request->noSurat;
        $data->judul = $request->judul;
        $data->deskripsi = $request->deskripsi;
        $data->jenis = $request->jenis;
        $data->berkas_catatan = '';
        $data->link_terkait = '';


        $data->save();
        return redirect()->route('produkHukum.index');
    }

    /**
     * edit
     *
     * @param  mixed $produkHukum
     * @return void
     */
    public function edit(request $request)
    {
        echo ($request["id"]);
        print_r($request->post());

        // $datas = ProdukHukum::latest()->when(request()->search, function ($data_dasars) {
        //     $data_dasars = $data_dasars->where('id', 'like', '%' . request()->id_usulan . '%');
        // })
        //     ->where('id', $_GET['id_usulan'])
        //     ->get();

        // session(['jenis' => $request->jenis]);

        // if (Session::get('level') == "verifikator") {
        //     return view('produkHukum.edit', compact('datas'));
        // } else if (Session::get('level') == "Biro Hukum") {
        //     return view('produkHukum.edit', compact('datas'));
        // } else {
        //     return view('produkHukum.detail', compact('datas'));
        // }
    }

    public function detailProdukHukum(Request $request)
    {
        $datas = ProdukHukum::latest()->when(request()->search, function ($data_dasars) {
            $data_dasars = $data_dasars->where('id', 'like', '%' . request()->id . '%');
        })
            ->where('id', $_GET['id'])
            ->get();

        return view('produkHukum.edit', compact('datas'));
    }


    /**
     * destroy
     *
     * @param  mixed $id
     * @return void
     */
    public function destroy($id)
    {
        $produkHukum = produkHukum::findOrFail($id);
        $produkHukum->delete();

        if ($produkHukum) {
            //redirect dengan pesan sukses
            return redirect()->route('produkHukum.index')->with(['pesan' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('produkHukum.index')->with(['pesan' => 'Data Gagal Dihapus!']);
        }
    }

    /**
     * update
     *
     * @param  mixed $request
     * @param  mixed $produkHukum
     * @return void
     */
    public function update(Request $request, produkHukum $produkHukum)
    {
        print_r($request->post());

        if ($request->has('file')) {
            $file = $request->file;

            $filename = time() . '.' . $file->getClientOriginalExtension();
            $request->file->move('assetes', $filename);

            $produkHukum->update([
                'berkas' => $filename,
            ]);
        }

        $produkHukum->update([
            'nomor_surat' => $request->noSurat,
            'judul' => $request->judul,
            'deskripsi' => $request->deskripsi,
            'jenis' => $request->jenis,
        ]);
        return redirect()->route('produkHukum.index');
    }
}

resources/views/produkHukum/create.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6 justify-between">
                <h1 class="text-3xl font-bold leading-tight mt-5 tracking-tight text-gray-900">PENGATURAN - Tambah Produk
                    Hukum</h1>
            </div>

            <form action="{{ route('produkHukum.store') }}" method="POST" enctype="multipart/form-data"
                class="-mx-4 ring-1 ring-gray-300 sm:mx-0 sm:rounded-md bg-white p-6 mb-10">
                @csrf

                <div class="space-y-12">
                    <div class="m grid gap-x-6 gap-y-8 flex col ">

                        <div class="col-span-full flex">
                            <label for="noSurat" class="place-self-center text-sm font-medium  text-gray-900 w-1/12">Nomor
                                Surat</label>
                            <input type="text" name="noSurat" id="noSurat" autocomplete="given-name"
                                class="block w-full   p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                        </div>

                        <div class="col-span-full flex">
                            <label for="judul" class="place-self-center text-sm font-medium  text-gray-900 w-1/12">Judul
                                Produk Hukum</label>
                            <input type="text" name="judul" id="judul" autocomplete="given-name"
                                class="block w-full   p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                        </div>

                        <div class="col-span-full flex">
                            <label for="nama"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Berkas</label>
                            <input id="file" type="file" name="file" accept=".doc, .docx, .pdf" />
                        </div>

                        <div class="col-span-full flex">
                            <label for="deskripsi"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Deskripsi</label>
                            <textarea type="text" name="deskripsi" id="deskripsi" rows="5"
                                class="block w-full   p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6"></textarea>
                        </div>

                        <div class="col-span-full flex">
                            <label for="jenis"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Jenis
                                File</label>
                            <select id="jenis" name="jenis" value="user"
                                class="p-2 block w-full rounded-md border-0 bg-white text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                                <option value="Perda">Perda</option>
                                <option value="Pergub">Pergub</option>
                                <option value="SK Gubernur">SK Gubernur</option>
                                <option value="SK Sekda">SK Sekda</option>
                                <option value="SK Kaban">SK Kaban</option>
                            </select>
                        </div>

                        <div class="col-span-full flex">
                            <label for="jenis"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Tanggal
                                Upload</label>
                            <input value="{{ date('Y-m-d') }}" disabled type="text" name="tgl" id="tgl"
                                class="block w-full   p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                        </div>

                    </div>
                </div>

                <div class="mt-6 flex items-center justify-end gap-x-2">
                    <button type="submit"
                        class="rounded-md bg-[#195243] px-3 py-2 text-sm font-semibold text-white shadow-sm  focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 ">Simpan</button>
                </div>


            </form>


        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/produkHukum/edit.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6 justify-between">
                <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">DETAIL PRODUK HUKUM</h1>
            </div>

            @forelse ($datas as $usulan)
            @empty
            @endforelse


            <form action="{{ route('produkHukum.update', $usulan->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="space-y-12 mt-10">
                    <div class="m grid gap-x-6 gap-y-8 flex col ">
                        <div class="col-span-full flex">
                            <label for="noSurat" class="place-self-center text-sm font-medium  text-gray-900 w-1/12">No
                                Surat</label>
                            <input value="{{ old('nip', $usulan->nomor_surat) }}" type="text" name="noSurat"
                                id="noSurat" autocomplete="given-name"
                                class="block w-full  p-2 rounded-md border-0  text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm">
                        </div>

                        <div class="col-span-full flex">
                            <label for="judul" class="place-self-center text-sm font-medium  text-gray-900 w-1/12">Judul
                                Berkas</label>
                            <input value="{{ old('nip', $usulan->judul) }}" type="text" name="judul" id="judul"
                                autocomplete="given-name"
                                class="block w-full  p-2 rounded-md border-0  text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm">
                        </div>

                        <div class="col-span-full flex">
                            <label for="nama"
                                class="place-self-top w-1/12 text-sm font-medium leading-6 text-gray-900">Berkas </label>
                            <div style="cle ar:both">
                                <iframe id="viewer" frameborder="0" scrolling="no" width="800" height="800"
                                    src="/assetes/{{ old('berkas', $usulan->berkas) }}"></iframe>
                            </div>
                        </div>

                        <div class="col-span-full flex">
                            <label for="nama"
                                class="place-self-top w-1/12 text-sm font-medium leading-6 text-gray-900">Berkas
                                Baru</label>

                            <input id="file" type="file" name="file" />
                        </div>

                        <div class="col-span-full flex">
                            <label for="deskripsi"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Deskripsi</label>
                            <textarea type="text" name="deskripsi" id="deskripsi"
                                {{ old('nip', $usulan->status) == 'Berkas Dikembalikan' ? '' : '' }} rows="5"
                                class="block w-full   p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">{{ old('nip', $usulan->deskripsi) }}</textarea>
                        </div>

                        <div class="col-span-full flex">
                            <label for="jenis"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Jenis
                                File</label>
                            <select id="jenis" name="jenis" value="user"
                                class="p-2 block w-full rounded-md border-0 bg-white text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                                <option value="Perda">Perda</option>
                                <option value="Pergub">Pergub</option>
                                <option value="SK Gubernur">SK Gubernur</option>
                                <option value="SK Sekda">SK Sekda</option>
                                <option value="SK Kaban">SK Kaban</option>
                            </select>
                        </div>

                        <div class="col-span-full flex">
                            <label for="jenis"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Tanggal
                                Upload</label>
                            <input value="{{ substr(old('nip', $usulan->updated_at), 0, 10) }}" type="text" name="tgl"
                                id="tgl" autocomplete="given-name"
                                class="block w-full   p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                        </div>

                    </div>
                </div>

                <div class="mt-10 flex items-center justify-end gap-x-2 mb-11">
                    <button type="submit"
                        class=  "rounded-md bg-[#195243] px-3 py-2 text-sm font-semibold text-white shadow-sm  ">
                        Ubah
                    </button>
                    <a
                        href="{{ (Session::get('level') == 'admin' or Session::get('subbidang') == 'Kab') ? '\resume' : '\resume' }}">
                        <button type="button"
                            class=  "rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm  ">
                            Kembali
                        </button>
                    </a>
                </div>
            </form>
        </div>
        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/produkHukum/index.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12 mb-20">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6  content-center ">
                <h1 class="text-4xl font-black font-sans leading-tight tracking-tight text-[#195243] py-4  rounded-full">
                    PRODUK HUKUM</h1>
                <a href="{{ route('produkHukum.create') }}" class="mt-1 ml-5">
                    <button type="button"
                        class="rounded-full bg-[#195243] px-3.5 py-2 mt-4 text-sm font-semibold text-white ring-gray-300">
                        Tambah Produk Hukum
                    </button>
                </a>
            </div>
            <div class="flex items-center gap-x-3 pb-6 ">
                <label for="photo" class="block text-sm font-bold text-black">Nama Produk Hukum</label>
                <input type="text" name="first-ame" id="first-name"
                    class="block w-full p-2 rounded-full border-0 py-1.5 text-black shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset sm:text-sm sm:leading-6">
                <button type="button"
                    class="inline-flex items-center rounded-full bg-[#195243] px-8 py-2 text-sm font-bold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                    Cari
                </button>
            </div>
            <div
                class="block w-full bg-white p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                <table class="min-w-full divide-y divide-gray-300 ">
                    <thead>
                        <tr>
                            <th scope="col" class="py-3 pl-5 pr-3 text-left text-sm font-semibold text-black">No Surat
                            </th>
                            <th scope="col" class="py-3 pl-5 pr-3 text-left text-sm font-semibold text-black">Judul</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-black">Deskripsi</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-black">Tgl Upload
                            </th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-black">Jenis</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-black">Pengaturan
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($selects as $data)
                            <tr class="border-b transition duration-300 ease-in-out items-center">
                                <td class="relative py-3 pl-5 pr-3 text-sm w-2/12">{{ $data->nomor_surat }}</td>
                                <td class="relative py-3 pl-5 pr-3 text-sm w-2/12">{{ $data->judul }}</td>
                                <td class="px-3 py-3.5 text-sm text-black">{{ $data->deskripsi }}</td>
                                <td class="px-3 py-3.5 text-sm text-black">{{ substr($data->created_at, 0, 10) }}</td>
                                <td class="px-3 py-3.5 text-sm text-black text-center">{{ $data->jenis }}</td>
                                <td class="px-3 py-3.5 text-sm text-black text-center">
                                    <div class="flex ">
                                        <form method="get" action="{{ route('detailProdukHukum') }}" class="items-center">
                                            <input type="text" name="id" id="id" value="{{ $data->id }}"
                                                hidden />
                                            <button type="submit"
                                                class="inline-flex items-center rounded-full bg-[#195243] px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                                                Ubah
                                            </button>
                                        </form>
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                            action="{{ route('produkHukum.destroy', $data->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit"
                                                class="inline-flex items-center rounded-full bg-red-700 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                                                Hapus
                                            </button>
                                        </form>
                                    </div>
                                </td>
                                </td>
                            </tr>
                        @empty
                            <div class="bg-red-500 text-white p-3  rounded shadow-sm">
                                <?php
                if (Session::get('level') == 'verifikator') {
                ?>
                                Semua usulan telah di Verifikasi
                                <?php
                } else {
                ?>
                                Data belum tersedia! tambah {{ basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)) }}
                                <?php
                }
                ?>
                            </div>
                        @endforelse

                        <!-- More plans... -->
                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection