routes/web.php
<?php

namespace App\Http\Controllers;

use App\Models\ProdukHukum;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/loginView', function () {
    return view('login');
});

Route::get('/dashboardPublic', function () {
    return view('dashboardPublic');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::get('/cariDashboardPublic', function () {
    return view('dashboardPublic');
});

Route::get('/caridashboard', function () {
    return view('dashboard');
});

Route::get('/password', function () {
    return view('pengaturan/password');
});

// Auth::routes();

Route::resource('pengaturan', PengaturanController::class);
Route::resource('usulan', UsulanController::class);
Route::resource('resume', ResumeController::class);
Route::resource('perda', PerdaController::class);
Route::resource('pergub', PergubController::class);
Route::resource('skgub', SkgubController::class);
Route::resource('skkaban', SkkabanController::class);
Route::resource('sksekda', SksekdaController::class);
Route::resource('user', UserController::class);
Route::resource('produkHukum', ProdukHukumController::class);
Route::resource('panduan', PanduanController::class);
Route::get('usulanAdmin', 'App\Http\Controllers\UsulanController@UsulanAdmin')->name('usulanAdmin');
Route::post('change-password', 'App\Http\Controllers\UserController@updatePassword')->name('update-password');
Route::post('uploadProdukPerda', 'App\Http\Controllers\PerdaController@uploadProdukPerda')->name('uploadProdukPerda');


Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('/cariusulan', [UsulanController::class, 'cariusulan'])->name('cariusulan');

Route::get('/usulanDetail', [UsulanController::class, 'usulanDetail'])->name('usulanDetail');
Route::get('/detailProdukHukum', [ProdukHukumController::class, 'detailProdukHukum'])->name('detailProdukHukum');
Route::get('/detailPanduan', [PanduanController::class, 'detailPanduan'])->name('detailPanduan');
Route::get('/resumeDetail', [ResumeController::class, 'resumeDetail'])->name('resumeDetail');
Route::get('/resumeDetailPublic', [ResumeController::class, 'resumeDetailPublic'])->name('resumeDetailPublic');
Route::get('/resumePublic', [ResumeController::class, 'resumePublic'])->name('resumePublic');
Route::get('/downloadPanduan', [PanduanController::class, 'downloadPanduan'])->name('downloadPanduan');

Route::get('/export', [ResumeController::class, 'export'])->name('export');

Route::get('/cariUsulanDetail', [UsulanController::class, 'cariUsulanDetail'])->name('cariUsulanDetail');
Route::get('/cariUsulanAdmin', [UsulanController::class, 'cariUsulanAdmin'])->name('cariUsulanAdmin');

Route::get('/exportResume', [ResumeController::class, 'exportexcel'])->name('exportResume');
Route::get('/cariResume', [ResumeController::class, 'cariResume'])->name('cariResume');

app/Models/User.php
<?php



namespace App\Models;



use Illuminate\Contracts\Auth\MustVerifyEmail;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Notifications\Notifiable;

use Laravel\Sanctum\HasApiTokens;

use Illuminate\Database\Eloquent\Casts\Attribute;



class User extends Authenticatable
{

    use HasApiTokens, HasFactory, Notifiable;



    /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = [

        'name',

        'email',

        'password',

        'type'

    ];



    /**

     * The attributes that should be hidden for serialization.

     *

     * @var array

     */

    protected $hidden = [

        'password',

        'remember_token',

    ];



    /**

     * The attributes that should be cast.

     *

     * @var array

     */

    protected $casts = [

        'email_verified_at' => 'datetime',

    ];



    /**

     * Interact with the user's first name.

     *

     * @param  string  $value

     * @return \Illuminate\Database\Eloquent\Casts\Attribute

     */

    protected function type(): Attribute
    {

        return new Attribute(

            get: fn($value) => ["user", "admin", "manager"][$value],

        );

    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Pengguna;
use Illuminate\Support\Facades\Hash;
use Session;
use Auth;

class UserController extends Controller
{
    public function index()
    {
        $selects = Pengguna::when(request()->search, function ($dosens) {
            $dosens = $dosens->where('nip', 'like', '%' . request()->search . '%');
        })->get();

        return view('user.index', compact('selects'));
    }

    /**
     * create
     *
     * @return void
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * store
     *
     * @param  mixed $request
     * @return void
     */
    public function store(Request $request)
    {
        // echo ("request");
        // print_r($request->post());
        // echo ($request["store"]);
        // $this->validate($request, [
        //     'kelas' => 'required',
        //     'singkatan' => 'required'
        // ]);

        $store = Pengguna::create([
            'nip' => $request->nip,
            'name' => $request->nama,
            'username' => $request->username,
            'password' => Hash::make($request->password),
            'level' => $request->slct1,
            'bidang' => $request->slct2,
            'subbidang' => $request->slct3,
        ]);

        if ($store) {
            //redirect dengan pesan sukses
            return redirect()->route('user.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('user.index')->with(['error' => 'Data Gagal Disimpan!']);
        }

    }


    public function updatePassword(Request $request)
    {
        $user = Auth::user();
        $user->password = Hash::make($request->new_password);
        $user->save();
        return redirect()->route('pengaturan.index');
    }


    /**
     * destroy
     *
     * @param  mixed $id
     * @return void
     */
    public function destroy($id)
    {
        $user = Pengguna::findOrFail($id);
        $user->delete();

        if ($user) {
            //redirect dengan pesan sukses
            return redirect()->route('user.index')->with(['pesan' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('user.index')->with(['pesan' => 'Data Gagal Dihapus!']);
        }
    }
}

resources/views/user/create.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6 justify-between">
                <h1 class="text-3xl font-bold leading-tight mt-5 tracking-tight text-gray-900">PENGATURAN - Tambah User</h1>
            </div>

            <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data"
                class="-mx-4 mt-10 ring-1 ring-gray-300 sm:mx-0 sm:rounded-lg bg-white p-6 mb-10">
                @csrf

                <div class="space-y-12">
                    <div class="m grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                        <div class="sm:col-span-3">
                            <label for="nip" class="block text-sm font-medium leading-6 text-gray-900">NIP</label>
                            <div class="mt-2">
                                <input type="text" name="nip" id="nip" autocomplete="family-name"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="nama" class="block text-sm font-medium leading-6 text-gray-900">Nama</label>
                            <div class="mt-2">
                                <input type="text" name="nama" id="nama" autocomplete="family-name"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                            <div class="mt-2">
                                <input type="text" name="username" id="username" autocomplete="given-name"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                            <div class="mt-2">
                                <input type="text" name="password" id="password"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="leveling" class="block text-sm font-medium leading-6 text-gray-900">Level</label>
                            <div class="mt-2">
                                <select id="slct1" name="slct1"
                                    class="p-2 block w-full rounded-md border-0 bg-white text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6"
                                    onchange="level(this.id, 'slct2')">
                                    <option value=""></option>
                                    <option value="uptd">Uptd</option>
                                    <option value="bidang">Bidang</option>
                                    <option value="verifikator">Verifikator</option>
                                    <option value="Biro Hukum">Biro Hukum</option>
                                </select>
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="leveling" class="block text-sm font-medium leading-6 text-gray-900">Bidang</label>
                            <div class="mt-2">
                                <select id="slct2" name="slct2"
                                    class="p-2 block w-full rounded-md border-0 bg-white text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6"
                                    onchange="bidang(this.id, 'slct3')">
                                </select>
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="leveling" class="block text-sm font-medium leading-6 text-gray-900">Jabatan</label>
                            <div class="mt-2">
                                <select id="slct3" name="slct3"
                                    class="p-2 block w-full rounded-md border-0 bg-white text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-6 flex items-center justify-end gap-x-2">
                    <button type="submit"
                        class="rounded-md bg-[#195243] px-3 py-2 text-sm font-semibold text-white shadow-sm ">SIMPAN</button>
                    <button
                        class="rounded-md bg-red-600 px-5 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600">BATAL</button>
                </div>
            </form>

        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>

    <script type="text/javascript">
        function level(s1, s2) {
            var s1 = document.getElementById(s1);
            var s2 = document.getElementById(s2);

            s2.innerHTML = "";

            if (s1.value == "uptd") {
                var optionArray = [
                    "|",
                    "Kota Samarinda|Kota Samarinda",
                    "Kota Bontang|Kota Bontang",
                    "Kota Balikpapan|Kota Balikpapan",
                    "Kabupaten Kubar|Kabupaten Kubar",
                    "Kabupaten Paser|Kabupaten Paser",
                    "Kabupaten Penajam Paser Utara|Kabupaten Penajam Paser Utara",
                    "Kabupaten Kutim|Kabupaten Kutim",
                    "Kabupaten Kukar|Kabupaten Kukar",
                    "Kabupaten Berau|Kabupaten Berau"
                ];
            } else if (s1.value == "bidang") {
                var optionArray = [
                    "|",
                    "Sekretaris|Sekretaris",
                    "Perencanaan & Pengembangan Sistem Informasi Pendapatan Pembina|Perencanaan & Pengembangan Sistem Informasi Pendapatan Pembina",
                    "Penerimaan Bukan Pajak Daerah Pembina Tingkat 1|Penerimaan Bukan Pajak Daerah Pembina Tingkat 1",
                    "Pajak Daerah Pembina Tingkat 1|Pajak Daerah Pembina Tingkat 1",
                    "Pengendalian & Evaluasi Pendapatan Pembina Tingat 1|Pengendalian & Evaluasi Pendapatan Pembina Tingat 1"
                ];
            } else if (s1.value == "verifikator") {
                var optionArray = [
                    "|",
                    "Staf|Staf"
                ];
            } else if (s1.value == "Biro Hukum") {
                var optionArray = [
                    "|",
                    "Staf Biro|Staf Biro"
                ];
            }

            for (var option in optionArray) {
                var pair = optionArray[option].split("|");
                var newOption = document.createElement("option");
                newOption.value = pair[0];
                newOption.innerHTML = pair[1];
                s2.options.add(newOption);
            }
        }

        function bidang(s2, s3) {
            var s2 = document.getElementById(s2);
            var s3 = document.getElementById(s3);

            s3.innerHTML = "";

            if (s2.value == "Sekretaris") {
                var optionArray = [
                    "Kabag Sekretaris Pembina|Kabag Sekretaris Pembina",
                    "Kasubag Umum Pembina|Kasubag Umum Pembina",
                    "Analisis Keuangan Pemerintah Pusat dan Daerah Ahli Muda Penata Tingkat 1|Analisis Keuangan Pemerintah Pusat dan Daerah Ahli Muda Penata Tingkat 1"
                ];
            } else if (s2.value == "Perencanaan & Pengembangan Sistem Informasi Pendapatan Pembina") {
                var optionArray = [
                    "Kabid Perencanaan & Pengembangan Sistem Informasi Pendapatan Pembina|Kabid Perencanaan & Pengembangan Sistem Informasi Pendapatan Pembina",
                    "Kasubid Analisis Pengembangan Pendapatan & Pelayanan Pembina|Kasubid Analisis Pengembangan Pendapatan & Pelayanan Pembina",
                    "Kasubid Perencanaan Anggaran Pendapatan & Pengembangan SIstem Informasi Pendapatan Penatan Tingkat 1|Kasubid Perencanaan Anggaran Pendapatan & Pengembangan SIstem Informasi Pendapatan Penatan Tingkat 1",
                ];
            } else if (s2.value == "Penerimaan Bukan Pajak Daerah Pembina Tingkat 1") {
                var optionArray = [
                    "Kabid Penerimaan Bukan Pajak Daerah Pembina Tingkat 1|Kabid Penerimaan Bukan Pajak Daerah Pembina Tingkat 1",
                    "Kasubbid Bagi Hasil Pajak & Bukan Pajak Penata Tingkat 1|Kasubbid Bagi Hasil Pajak & Bukan Pajak Penata Tingkat 1",
                    "Kasubbid Retribusi Daerah Pembina|Kasubbid Retribusi Daerah Pembina",
                ];
            } else if (s2.value == "Pajak Daerah Pembina Tingkat 1") {
                var optionArray = [
                    "Kabid Pajak Daerah Pembina Tingkat 1|Kabid Pajak Daerah Pembina Tingkat 1",
                    "Kasubbid Pkb dan Bbkkb Penata Tingkat 1|Kasubbid Pkb dan Bbkkb Penata Tingkat 1",
                    "Kasubbid Pendapatan Administrasi dan Ratan Pajak Pembina|Kasubbid Pendapatan Administrasi dan Ratan Pajak Pembina",
                ];
            } else if (s2.value == "Pengendalian & Evaluasi Pendapatan Pembina Tingat 1") {
                var optionArray = [
                    "Kabid Pengendalian & Evaluasi Pendapatan Pembina Tingkat 1|Kabid Pengendalian & Evaluasi Pendapatan Pembina Tingkat 1",
                    "Kasubbid Pengendalian & Evaluasi Pendapatan Pembina|Kasubbid Pengendalian & Evaluasi Pendapatan Pembina",
                    "Kasubbid Kajuan Hukun & Perundang Undangan Penata|Kasubbid Kajuan Hukun & Perundang Undangan Penata",
                ];
            } else if (s2.value == "Staf") {
                var optionArray = [
                    "|",
                    "Staf 1 (Perda, Pergub, SK Gub)|Staf 1 (Perda, Pergub, SK Gub)",
                    "Staf 2 (SK Sekda, SK Kaban)|Staf 2 (SK Sekda, SK Kaban)"
                ];
            } else if (s2.value == "Staf Biro") {
                var optionArray = [
                    "|",
                    "Staf|Staf"
                ];
            } else {
                var optionArray = [
                    "|",
                    "Kepala TU|Kepala TU",
                    "Kasubag TU|Kasubag TU"
                ];
            }

            for (var option in optionArray) {
                var pair = optionArray[option].split("|");
                var newOption = document.createElement("option");
                newOption.value = pair[0];
                newOption.innerHTML = pair[1];
                s3.options.add(newOption);
            }
        }
    </script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12">
        <div>
            <div class="hidden sm:-my-px sm:flex py-6 justify-between">
                <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">PENGATURAN - Tambah User</h1>
            </div>

            <form action="{{ route('pengaturan.update', $pengaturan->id) }}" method="POST" enctype="multipart/form-data"
                class="-mx-4 ring-1 ring-gray-300 sm:mx-0 sm:rounded-lg bg-white p-6 mb-10">
                @csrf
                @method('PUT')

                <div class="space-y-12">
                    <div class="m grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                        <div class="sm:col-span-3">
                            <label for="nama" class="block text-sm font-medium leading-6 text-gray-900">Nama</label>
                            <div class="mt-2">
                                <input type="text" name="nama" id="nama" autocomplete="family-name"
                                    value="{{ old('name', $pengaturan->name) }}"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                            <div class="mt-2">
                                <input type="text" name="username" id="username" autocomplete="given-name"
                                    value="{{ old('username', $pengaturan->username) }}"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                            <div class="mt-2">
                                <input type="text" name="password" id="password"
                                    value="{{ old('password', $pengaturan->password) }}"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="leveling" class="block text-sm font-medium leading-6 text-gray-900">Leveling</label>
                            <div class="mt-2">
                                <input type="text" name="level" id="level"
                                    value="{{ old('level', $pengaturan->level) }}"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="bidang" class="block text-sm font-medium leading-6 text-gray-900">Bidang</label>
                            <div class="mt-2">
                                <input type="text" name="bidang" id="bidang"
                                    value="{{ old('bidang', $pengaturan->bidang) }}"
                                    class="block w-full p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-6 flex items-center justify-end gap-x-2">
                    <button type="submit"
                        class="rounded-md bg-[#195243] px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#195243]">Simpan</button>
                    <button
                        class="rounded-md bg-red-700 px-5 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-700">Batal</button>
                </div>
            </form>

        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12 mb-20">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6  content-center ">
                <h1 class="text-4xl font-black font-sans leading-tight tracking-tight text-[#195243] py-4  rounded-full">USER
                </h1>
                <a href="{{ route('user.create') }}" class="mt-1 ml-5">
                    <button type="button"
                        class="rounded-full bg-[#195243] px-3.5 py-2 mt-4 text-sm font-semibold text-white ring-gray-300">
                        Tambah User
                    </button>
                </a>
            </div>
            <!-- <div class="flex items-center gap-x-3 pb-6 ">
              <label for="photo" class="block text-sm font-bold text-black">NAMA PENGGUNA</label>
              <input type="text" name="first-ame" id="first-name" class="block w-full p-2 rounded-full border-0 py-1.5 text-black shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset sm:text-sm sm:leading-6">
              <button type="button" class="inline-flex items-center rounded-full bg-[#195243] px-8 py-2 text-sm font-bold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                Cari
              </button>
            </div> -->
            <div
                class="block w-full bg-white p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                <table class="min-w-full divide-y divide-gray-300 ">
                    <thead>
                        <tr>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-bold uppercase">Nama</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-bold uppercase">Username</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-bold uppercase">Level</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-bold uppercase">Bidang</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-bold uppercase">Jabatan</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-bold uppercase">Pengaturan</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($selects as $data)
                            <tr class="border-b transition duration-300 ease-in-out">
                                <td class="px-3 py-3.5 text-sm text-black">{{ $data->name }}</td>
                                <td class="px-3 py-3.5 text-sm text-black text-center">{{ $data->username }}</td>
                                <td class="px-3 py-3.5 text-sm text-black text-center uppercase">{{ $data->level }}</td>
                                <td class="px-3 py-3.5 text-sm text-black text-center uppercase">{{ $data->bidang }}</td>
                                <td class="px-3 py-3.5 text-sm text-black text-center uppercase">{{ $data->subbidang }}</td>
                                <td class="relative py-3.5 pl-3 pr-4 text-center text-sm font-medium flex justify-center">
                                    <!-- <a href="{{ route('user.edit', $data->id) }}" class="mr-2">
                    <button type="button" class="inline-flex items-center rounded-full bg-[#195243] px-3.5 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                      Ubah
                    </button>
                  </a> -->
                                    <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                        action="{{ route('user.destroy', $data->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="inline-flex items-center rounded-full bg-red-700 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                                            Hapus
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <div class="bg-red-500 text-white p-3  rounded shadow-sm">
                                Data belum tersedia! tambah {{ basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)) }}
                            </div>
                        @endforelse

                        <!-- More plans... -->
                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection