routes/web.php
<?php

namespace App\Http\Controllers;

use App\Models\ProdukHukum;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginRegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/loginView', function () {
    return view('login');
});

Route::get('/dashboardPublic', function () {
    return view('dashboardPublic');
});

Route::get('/dashboard', function () {
    return view('dashboard');
});

Route::get('/cariDashboardPublic', function () {
    return view('dashboardPublic');
});

Route::get('/caridashboard', function () {
    return view('dashboard');
});

Route::get('/password', function () {
    return view('pengaturan/password');
});

// Auth::routes();

Route::resource('pengaturan', PengaturanController::class);
Route::resource('usulan', UsulanController::class);
Route::resource('resume', ResumeController::class);
Route::resource('perda', PerdaController::class);
Route::resource('pergub', PergubController::class);
Route::resource('skgub', SkgubController::class);
Route::resource('skkaban', SkkabanController::class);
Route::resource('sksekda', SksekdaController::class);
Route::resource('user', UserController::class);
Route::resource('produkHukum', ProdukHukumController::class);
Route::resource('panduan', PanduanController::class);
Route::get('usulanAdmin', 'App\Http\Controllers\UsulanController@UsulanAdmin')->name('usulanAdmin');
Route::post('change-password', 'App\Http\Controllers\UserController@updatePassword')->name('update-password');
Route::post('uploadProdukPerda', 'App\Http\Controllers\PerdaController@uploadProdukPerda')->name('uploadProdukPerda');


Route::get('login', 'App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login', 'App\Http\Controllers\AuthController@proses_login')->name('proses_login');
Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');
Route::get('/cariusulan', [UsulanController::class, 'cariusulan'])->name('cariusulan');

Route::get('/usulanDetail', [UsulanController::class, 'usulanDetail'])->name('usulanDetail');
Route::get('/detailProdukHukum', [ProdukHukumController::class, 'detailProdukHukum'])->name('detailProdukHukum');
Route::get('/detailPanduan', [PanduanController::class, 'detailPanduan'])->name('detailPanduan');
Route::get('/resumeDetail', [ResumeController::class, 'resumeDetail'])->name('resumeDetail');
Route::get('/resumeDetailPublic', [ResumeController::class, 'resumeDetailPublic'])->name('resumeDetailPublic');
Route::get('/resumePublic', [ResumeController::class, 'resumePublic'])->name('resumePublic');
Route::get('/downloadPanduan', [PanduanController::class, 'downloadPanduan'])->name('downloadPanduan');

Route::get('/export', [ResumeController::class, 'export'])->name('export');

Route::get('/cariUsulanDetail', [UsulanController::class, 'cariUsulanDetail'])->name('cariUsulanDetail');
Route::get('/cariUsulanAdmin', [UsulanController::class, 'cariUsulanAdmin'])->name('cariUsulanAdmin');

Route::get('/exportResume', [ResumeController::class, 'exportexcel'])->name('exportResume');
Route::get('/cariResume', [ResumeController::class, 'cariResume'])->name('cariResume');

app/Models/Panduan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Panduan extends Model
{

    use HasFactory, Sortable;
    public $table = "panduan";

    protected $fillable = [
        'level',
        'panduan'
    ];
}

app/Http/Controllers/PanduanController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Models\Panduan;
use Session;
use Response;


class panduanController extends Controller
{

    public function index()
    {
        // $selects = DB::table('panduan')
        //     ->get();

        $selects = Panduan::sortable()->paginate(5);

        return view('panduan.index', compact('selects'));
    }

    /**
     * create
     *
     * @return void
     */
    public function create()
    {
        return view('panduan.create');
    }

    /**
     * store
     *
     * @param  mixed $request
     * @return void
     */

    /**
     * edit
     *
     * @param  mixed $panduan
     * @return void
     */
    public function edit(request $request)
    {
        $datas = panduan::latest()->when(request()->search, function ($data_dasars) {
            $data_dasars = $data_dasars->where('id', 'like', '%' . request()->id . '%');
        })
            ->where('id', $_GET['id'])
            ->get();

        return view('panduan.edit', compact('datas'));
    }

    /**
     * destroy
     *
     * @param  mixed $id
     * @return void
     */
    public function destroy($id)
    {
        $panduan = panduan::findOrFail($id);
        $panduan->delete();

        if ($panduan) {
            //redirect dengan pesan sukses
            return redirect()->route('panduan.index')->with(['pesan' => 'Data Berhasil Dihapus!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('panduan.index')->with(['pesan' => 'Data Gagal Dihapus!']);
        }
    }

    /**
     * update
     *
     * @param  mixed $request
     * @param  mixed $panduan
     * @return void
     */
    public function update(Request $request, panduan $panduan)
    {
        print_r($request->post());

        if ($request->has('file')) {
            $file = $request->file;

            $filename = time() . '.' . $file->getClientOriginalExtension();
            $request->file->move('assetes', $filename);

            $panduan->update([
                'panduan' => $filename,
            ]);
        }

        return redirect()->route('panduan.index');
    }

    public function detailPanduan(Request $request)
    {
        $datas = Panduan::latest()->when(request()->search, function ($data_dasars) {
            $data_dasars = $data_dasars->where('id', 'like', '%' . request()->id . '%');
        })
            ->where('id', $_GET['id'])
            ->get();

        return view('panduan.detail', compact('datas'));
    }

    public function downloadPanduan()
    {
        $file = public_path() . "/assetes/" . $_GET['id'];
        $headers = array('Content-Type: application/pdf', );
        return Response::download($file, 'panduan.pdf', $headers);
    }


}

resources/views/panduan/detail.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6 justify-between">
                <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">
                    {{ isset($_GET['ubah']) ? 'UBAH' : 'DETAIL' }} PANDUAN</h1>
            </div>

            @forelse ($datas as $usulan)
            @empty
            @endforelse



            <form action="{{ route('panduan.update', $usulan->id) }}" method="POST" enctype="multipart/form-data"
                class="mt-10">
                @csrf
                @method('PUT')

                <div class="">
                    <div class="">

                        <div class="col-span-full flex mb-5">
                            <label for="nama"
                                class="place-self-top w-1/12 text-sm font-medium leading-6 text-gray-900">Panduan
                                Lama</label>
                            <div style="clear:both">
                                <iframe id="viewer" frameborder="0" scrolling="no" width="800" height="800"
                                    src="/assetes/{{ old('berkas', $usulan->panduan) }}"></iframe>
                            </div>
                        </div>

                        <?php
                    if (isset($_GET['ubah'])){
                ?>
                        <div class="col-span-full flex mt-5">
                            <label for="nama"
                                class="place-self-center w-1/12 text-sm font-medium leading-6 text-gray-900">Panduan
                                Baru</label>
                            <input id="file" type="file" name="file" accept=".doc, .docx, .pdf">
                        </div>
                        <div class="mt-6 flex items-center justify-end gap-x-2 mb-2">
                            <button type="submit"
                                class="w-full py-3 rounded-md bg-[#195243] px-3 py-2 text-md font-semibold text-white shadow-sm  ">
                                SIMPAN
                            </button>
                        </div>
                        <?php
                    }else{}
                ?>

                        <div class=" block  gap-x-2  mb-10">
                            <a href="/panduan" class="block">
                                <button type="button"
                                    class="w-full py-3 rounded-md bg-[#195243] px-3 py-2 text-md font-semibold text-white shadow-sm  ">
                                    KEMBALI
                                </button>
                            </a>
                        </div>
                    </div>
                </div>



            </form>
        </div>
        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/panduan/edit.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6 justify-between">
                <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">DETAIL PANDUAN</h1>
            </div>

            @forelse ($datas as $usulan)
            @empty
            @endforelse



            <form action="{{ route('usulan.update', $usulan->id) }}" method="POST" enctype="multipart/form-data"
                class="mt-10">
                @csrf
                @method('PUT')

                <div class="space-y-12">
                    <div class="m grid gap-x-6 gap-y-8 flex col ">
                        <div class="col-span-full flex">
                            <label for="level" class="place-self-center text-sm font-medium  text-gray-900 w-1/12">level
                                User</label>
                            <input value="{{ old('nip', $usulan->level) }}" disabled type="text" name="level"
                                id="level" autocomplete="given-name"
                                class="block w-full  p-2 rounded-md border-0  text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm">
                        </div>

                        <div class="col-span-full flex">
                            <label for="nama"
                                class="place-self-top w-1/12 text-sm font-medium leading-6 text-gray-900">Berkas</label>
                            <div style="clear:both">
                                <iframe id="viewer" frameborder="0" scrolling="no" width="800" height="800"
                                    src="/assetes/{{ old('berkas', $usulan->panduan) }}"></iframe>
                            </div>
                        </div>

                        <hr />
                    </div>
                </div>

                <div class="mt-10 flex items-center justify-end gap-x-2 mb-11">
                    <a href="/panduan">
                        <button type="button"
                            class=  "rounded-md bg-[#195243] px-3 py-2 text-sm font-semibold text-white shadow-sm  ">
                            Kembali
                        </button>
                    </a>
                </div>
            </form>
        </div>
        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/panduan/index.blade.php
@extends('layouts.navbar', ['title' => 'Dashboard'])

@section('content')
    <main class="bg-bgColor h-screen px-12 mb-20">
        <div>
            <img class="right-14 top-6 absolute h-18 w-16" src="/images/logo_prov_kaltim.png" alt=""></img>
            <img class="right-32 top-8 absolute h-16 w-auto" src="/images/logo_bapenda_kaltim.png" alt=""></img>
            <div class="hidden sm:-my-px sm:flex py-6  content-center ">
                <h1 class="text-4xl font-black font-sans leading-tight tracking-tight text-[#195243] py-4  rounded-full">
                    PANDUAN</h1>
            </div>
            <div
                class="block w-full bg-white p-2 rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400  sm:text-sm sm:leading-6">
                <table class="min-w-full divide-y divide-gray-300 ">
                    <thead>
                        <tr>
                            <th scope="col" class="py-3 pl-5 pr-3 text-left text-sm font-semibold text-black">
                                @sortablelink('Level')</th>
                            <th scope="col" class="py-3 pl-5 pr-3 text-left text-sm font-semibold text-black">
                                @sortablelink('Panduan')</th>
                            <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-black">
                                @sortablelink('Pengaturan')</th>
                        </tr>
                    </thead>
                    <?php
                    $pengupload = DB::table('panduan')
                        ->latest()
                        ->get(); ?>

                    <tbody>
                        @forelse($selects as $data)
                            <tr class="border-b transition duration-300 ease-in-out">
                                <td class="relative py-3 pl-5 pr-3 text-sm w-2/12">
                                    {{ $data->level == 'Biro Umum' ? 'Biro Hukum' : ($data->level == 'Kasub / Kabid' ? 'Kepala' : ($data->level == 'Kepala TU' ? 'Kasubag' : $data->level)) }}
                                </td>
                                <td class="relative py-3 pl-5 pr-3 text-sm w-2/12"> </td>
                                <td
                                    class="relative py-3.5 pl-3 pr-4 text-center text-sm font-medium flex justify-center gap-2">
                                    <form method="get" action="{{ route('detailPanduan') }}" class="items-center">
                                        <input type="text" name="id" id="id" value="{{ $data->id }}"
                                            hidden />
                                        <button type="submit"
                                            class="inline-flex items-center rounded-full bg-[#195243] px-6 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                                            Lihat
                                        </button>
                                    </form>
                                    <form method="get" action="/downloadPanduan" class="items-center">
                                        <input type="text" name="id" id="id" value="{{ $data->panduan }}"
                                            hidden />
                                        <button type="submit"
                                            class="inline-flex items-center rounded-full bg-[#195243] px-6 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                                            Download
                                        </button>
                                    </form>
                                    <form method="get" action="{{ route('detailPanduan') }}" class="items-center">
                                        <input type="text" name="id" id="id" value="{{ $data->id }}"
                                            hidden />
                                        <input type="text" name="ubah" id="ubah" value="ubah" hidden />
                                        <button type="submit"
                                            class="inline-flex items-center rounded-full bg-[#195243] px-6 py-1.5 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-gray-300">
                                            Ubah
                                        </button>
                                    </form>

                                </td>
                                </td>
                            </tr>
                        @empty
                        @endforelse

                        <!-- More plans... -->
                    </tbody>
                </table>
                <!-- {!! $selects->appends(\Request::except('page'))->render() !!} -->
            </div>
        </div>
    </main>

    <script src="https://cdn.ckeditor.com/4.12.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection